name: Terraform - Create ironman User

on:
  push:
    branches: [ main ]
    paths:
      - "ironman-user/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ironman-user
        run: terraform init

      - name: Terraform Validate
        working-directory: ironman-user
        run: terraform validate

      - name: Terraform Plan
        working-directory: ironman-user
        run: terraform plan

      - name: Terraform Apply
        working-directory: ironman-user
        run: terraform apply -auto-approve